version: "3.9"

volumes:
  dbdata:

services:
  db:
    image: postgres:14.5-bullseye
    container_name: postgres
    # volumes:
    #   - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
